feat: inserts added for Database, usuario-antecedente_paciente
ElrohirGT/Sanitas pull request #21
Opened 2024-04-10 01:02 UTC by DanielDubon

# ClickUp

[Link al issue en ClickUp](Link%20al%20clickup)

## Descripción

Se actualizaron la lista de los reviewers para el backend

## Tasks

- \[ \] Asignate a tí mismo dentro de la PR.
- \[ \] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[ \] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[ \] Agrega el link al issue de ClickUp.
- \[ \] Asegurate que la PR pase todos los chequeos de CI.
- \[ \] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-04-10 01:03 UTC, DanielDubon commented
Añadi inserts para las tablas desde usuario hasta antecedente_paciente

2024-04-10 01:06 UTC, BiancaCalderon approved these changes

2024-04-10 01:09 UTC, BiancaCalderon approved these changes

2024-04-10 01:13 UTC, ElrohirGT requested changes
Faltan inserts

2024-04-10 01:21 UTC, ElrohirGT requested changes
Falta agregar el archivo al Nix!

2024-04-11 02:33 UTC, ElrohirGT approved these changes

2024-04-11 02:33 UTC, merged