feat: dprint formatter added
ElrohirGT/Sanitas pull request #25
Opened 2024-04-18 23:45 UTC by DanielDubon

# ClickUp

[Link al issue en ClickUp](Link%20al%20clickup)

## Descripción

Se actualizaron la lista de los reviewers para el backend

## Tasks

- \[ ] Asignate a tí mismo dentro de la PR.
- \[ ] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[ ] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[ ] Agrega el link al issue de ClickUp.
- \[ ] Asegurate que la PR pase todos los chequeos de CI.
- \[ ] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-04-18 23:45 UTC, DanielDubon commented
Añadi el dprint para formatear el codigo y el script para Yarn, el comando es "yarn run format"

2024-04-19 00:24 UTC, ElrohirGT requested changes
Excelente! Podrías agregar otro commit en donde corres el comando y te formatea los archivos porfa? Así ya está todo bien formateadito jaja

2024-04-19 00:37 UTC, DanielDubon commented
Corri el comando y se formateo el codigo!

2024-04-19 00:41 UTC, ElrohirGT approved these changes

2024-04-19 00:43 UTC, merged